server:
  port: 80

spring:
  application:
    name: alibaba-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/

service-url:
  provider-payment-service: http://alibaba-provider-payment
