server:
  port: 9002

spring:
  application:
    name: alibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: http://169.254.63.133:8848/
      sentinel:
        transport:
          dashboard: localhost:8080
          port: 8719