server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: top.lhzcc.springcloud.entities
  mapper-locations: classpath:mapper/*.xml
