server:
  port: 84

spring:
  application:
    name: alibaba-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true